"""
Split Module 7 (CSS Grid and Flex Box) into two separate modules.

Module 7 of CIS 195 covers CSS Grid and CSS Flexbox together. This script
creates two new modules at the bottom of the Modules page, one per topic:

    CSS Grid
    CSS Flexbox

Both are created UNPUBLISHED, so they are hidden from students. Module 7 is
left completely untouched - nothing is moved, edited, or deleted.

Items that genuinely cover both topics (Lab 6, the South India demo site) are
added to both new modules. The combined CSS Handbook reading page is split so
each module lists only its own chapter. Section labels ("Reading", "Lecture
Notes", ...) are SubHeader module items rather than the standalone header Pages
Module 7 uses, matching the newer convention in Module 8 and "Advanced CSS".

A few Canvas course-design conventions are applied on top of the Module 7
content:
  - Items are indented under their SubHeader for visual grouping.
  - Each module requires viewing its overview page and submitting Lab 6 to
    be marked complete.
  - The Flexbox module is locked behind the Grid module's completion
    (prerequisite_module_ids), so students see them in order once published.
  - Each overview page states the estimated time and completion requirements.

  Dry run (default):
    Prints every module, page, and item that would be created. Makes NO
    connection to Canvas and NO changes whatsoever.

  Apply mode (--apply):
    Connects to Canvas, shows the same plan, then asks for confirmation
    before creating anything.

Usage:
    python split_grid_flexbox_modules.py           # dry run - preview only
    python split_grid_flexbox_modules.py --apply   # connect, confirm, create
"""
import os
import sys
import argparse
from dotenv import load_dotenv
from canvasapi import Canvas

# Windows consoles default to cp1252, which can't encode the emoji used in the
# progress output. Fall back gracefully rather than crashing mid-run.
for _stream in (sys.stdout, sys.stderr):
    if hasattr(_stream, "reconfigure"):
        _stream.reconfigure(encoding="utf-8", errors="replace")

# Load environment variables from .env file
# This keeps credentials out of your code
load_dotenv()

# Retrieve Canvas API credentials from environment variables
CANVAS_URL = os.getenv('CANVAS_URL')
CANVAS_TOKEN = os.getenv('CANVAS_TOKEN')
COURSE_ID_STR = os.getenv('COURSE_ID')

# Canvas content IDs carried over from Module 7. These are course-specific and
# were read from the course export in downloads/.
LAB6_ASSIGNMENT_ID = 22045      # "Lab 6 Submission"
GRID_DEMOS_FILE_ID = 73039      # "CssGridDemos.zip"
GRID_IMAGE_FILE_ID = 73057      # grid-paper illustration used on the overview page

LAB6_INSTRUCTIONS_URL = "https://lcc-cit.github.io/CIS195-CourseMaterials/LabStarters/Lab06/Lab6Instructions_8wk.html"
SOUTH_INDIA_DEMO_URL = "https://lcc-cit.github.io/CIS195-Demos/Unit05_GridAndFlexbox/Finished/"


# ---------------------------------------------------------------------------
# Page bodies for the new modules
#
# The overview pages are adapted from the Module 7 overview page, minus its
# week/date banner - these modules aren't tied to a specific week.
# The reading pages split the combined "Selected Sections of The CSS Handbook"
# page into its Grid chapter and its Flexbox chapter.
# ---------------------------------------------------------------------------

GRID_OVERVIEW_BODY = f"""<div class="summary expanded">
  <div class="no-overflow">
    <figure style="float: right;">
      <img src="https://canvas.lanecc.edu/courses/1196/files/{GRID_IMAGE_FILE_ID}/preview" alt="Woman drawing squares on grid paper." class="img-fluid atto_image_button_text-bottom" width="200" height="200" loading="lazy" data-api-endpoint="https://canvas.lanecc.edu/api/v1/courses/1196/files/{GRID_IMAGE_FILE_ID}" data-api-returntype="File">
      <figcaption>Image generated by AI</figcaption>
    </figure>
    <h2>Overview</h2>
    <p dir="ltr" style="text-align: left;">In this module you will learn to control the layout of a page with <strong>CSS Grid</strong>, a two-dimensional layout system that arranges content into rows and columns.</p>
    <p dir="ltr" style="text-align: left;">By the end of this module you should be able to:</p>
    <ul dir="ltr">
      <li style="text-align: left;">Define a grid container and set up grid rows and columns</li>
      <li style="text-align: left;">Place elements into specific grid areas</li>
      <li style="text-align: left;">Use the <code>gap</code> property to space grid items</li>
      <li style="text-align: left;">Choose CSS Grid over other layout techniques when it is the better fit</li>
    </ul>
    <p dir="ltr" style="text-align: left;"><strong>Estimated time:</strong> 2-3 hours (reading, lecture notes, and Lab 6).</p>
    <p dir="ltr" style="text-align: left;"><strong>To complete this module:</strong> view this page and submit Lab 6.</p>
    <p dir="ltr" style="text-align: left;"><em>Note: Lab 6 covers both Grid and Flexbox. It appears in both modules for convenience, but you only need to submit it once.</em></p>
  </div>
</div>"""

FLEXBOX_OVERVIEW_BODY = """<div class="summary expanded">
  <div class="no-overflow">
    <h2>Overview</h2>
    <p dir="ltr" style="text-align: left;">In this module you will learn to control the layout of a page with <strong>CSS Flexbox</strong>, a one-dimensional layout system that distributes content along a single row or column.</p>
    <p dir="ltr" style="text-align: left;">By the end of this module you should be able to:</p>
    <ul dir="ltr">
      <li style="text-align: left;">Define a flex container and set its main axis with <code>flex-direction</code></li>
      <li style="text-align: left;">Align and distribute flex items with <code>justify-content</code> and <code>align-items</code></li>
      <li style="text-align: left;">Control how flex items grow, shrink, and wrap</li>
      <li style="text-align: left;">Choose CSS Flexbox over other layout techniques when it is the better fit</li>
    </ul>
    <p dir="ltr" style="text-align: left;"><strong>Estimated time:</strong> 2-3 hours (reading, lecture notes, and Lab 6).</p>
    <p dir="ltr" style="text-align: left;"><strong>To complete this module:</strong> view this page and submit Lab 6.</p>
    <p dir="ltr" style="text-align: left;"><em>Note: Lab 6 covers both Grid and Flexbox. It appears in both modules for convenience, but you only need to submit it once.</em></p>
  </div>
</div>"""

GRID_READING_BODY = """<p>Selected Sections of <a href="https://flaviocopes.com/book/css/" target="_blank"><em>The CSS Handbook</em></a> by Flavio Copes</p>
<ul>
<li>
<a href="https://flaviocopes.com/book/css/#31-css-grid" target="_blank">31. CSS Grid</a>
<ul><li>Note: this chapter refers to the CSS2 property <code>grid-gap</code>, which is now deprecated and replaced by the CSS3 property <code>gap</code>.</li></ul>
</li>
</ul>"""

FLEXBOX_READING_BODY = """<p>Selected Sections of <a href="https://flaviocopes.com/book/css/" target="_blank"><em>The CSS Handbook</em></a> by Flavio Copes</p>
<ul>
<li><a href="https://flaviocopes.com/book/css/#32-flexbox" target="_blank">32. Flexbox</a></li>
</ul>"""


# ---------------------------------------------------------------------------
# The two modules, described as data.
#
# Each item is a dict matching the Canvas module-item API. Items of type "Page"
# carry an extra "body" key: the page is created first, then the module item is
# pointed at it by page_url. "require" marks a completion requirement
# ("must_view" or "must_submit"); items without it have none. Items are
# indented one level under their most recent SubHeader (see compute_indents).
# ---------------------------------------------------------------------------

MODULES = [
    {
        "name": "CSS Grid",
        "items": [
            {"type": "Page", "title": "CSS Grid", "body": GRID_OVERVIEW_BODY, "require": "must_view"},
            {"type": "SubHeader", "title": "Reading"},
            {"type": "Page", "title": "Reading: CSS Grid", "body": GRID_READING_BODY},
            {"type": "SubHeader", "title": "Lecture Notes"},
            {"type": "ExternalUrl", "title": "Positioning with CSS Grid",
             "external_url": "https://lcc-cit.github.io/CIS195-CourseMaterials/LectureNotes/CIS195-LN-W06-D2A-CssGrid.html"},
            {"type": "SubHeader", "title": "Recordings"},
            {"type": "ExternalUrl", "title": "Week 7, Tuesday lecture recording",
             "external_url": "https://lanecc.zoom.us/rec/share/Uc7MV58IKxT0WjJJJGeNLpXIVXDDkA-gCDXvJcvC1Ja-ZCdvSgl_cnOx9q8mzx3k.NoCD0e_5dhbhO6T_"},
            {"type": "SubHeader", "title": "Examples"},
            {"type": "ExternalUrl", "title": "South India Site with Grid and Flexbox",
             "external_url": SOUTH_INDIA_DEMO_URL},
            {"type": "ExternalUrl", "title": "CSS Grid Examples",
             "external_url": "https://lcc-cit.github.io/CIS195-CourseMaterials/Examples/LayoutDemos/cssGridExample.html"},
            {"type": "File", "title": "In-class grid demos—summer 2023",
             "content_id": GRID_DEMOS_FILE_ID},
            {"type": "SubHeader", "title": "Activities"},
            {"type": "ExternalUrl", "title": "Lab 6 Instructions",
             "external_url": LAB6_INSTRUCTIONS_URL},
            {"type": "Assignment", "title": "Lab 6 Submission",
             "content_id": LAB6_ASSIGNMENT_ID, "require": "must_submit"},
        ],
    },
    {
        "name": "CSS Flexbox",
        "prerequisite": "CSS Grid",
        "items": [
            {"type": "Page", "title": "CSS Flexbox", "body": FLEXBOX_OVERVIEW_BODY, "require": "must_view"},
            {"type": "SubHeader", "title": "Reading"},
            {"type": "Page", "title": "Reading: CSS Flexbox", "body": FLEXBOX_READING_BODY},
            {"type": "SubHeader", "title": "Lecture Notes"},
            {"type": "ExternalUrl", "title": "Positioning with CSS Flexbox",
             "external_url": "https://lcc-cit.github.io/CIS195-CourseMaterials/LectureNotes/CIS195-LN-W06-D2B-CssFlexBox.html"},
            {"type": "SubHeader", "title": "Recordings"},
            {"type": "ExternalUrl", "title": "Week 7, Thursday lecture recording",
             "external_url": "https://lanecc.zoom.us/rec/share/av6CumGQEahnrqY1jrP-Yr708ZTv7QrsKL9b12LoxgsMIAObMeaCIVKp47VLSB0n.URz-Xhqi7m8h2cqx"},
            {"type": "SubHeader", "title": "Examples"},
            {"type": "ExternalUrl", "title": "South India Site with Grid and Flexbox",
             "external_url": SOUTH_INDIA_DEMO_URL},
            {"type": "SubHeader", "title": "Activities"},
            {"type": "ExternalUrl", "title": "Lab 6 Instructions",
             "external_url": LAB6_INSTRUCTIONS_URL},
            {"type": "Assignment", "title": "Lab 6 Submission",
             "content_id": LAB6_ASSIGNMENT_ID, "require": "must_submit"},
        ],
    },
]


def compute_indents(items):
    """Indent level for each item: 0 for SubHeaders (and anything before the
    first one, i.e. the overview page), 1 for everything grouped under the
    most recently seen SubHeader."""
    indents = []
    indent = 0
    for item in items:
        if item["type"] == "SubHeader":
            indent = 0
            indents.append(indent)
            indent = 1
        else:
            indents.append(indent)
    return indents


def confirm(prompt):
    """Ask a yes/no question on the console. Only an explicit 'y'/'yes' counts as approval."""
    answer = input(f"{prompt} [y/N]: ").strip().lower()
    return answer in ("y", "yes")


def print_plan(dry_run):
    print("\n" + "=" * 60)
    print("DRY RUN - no changes will be made" if dry_run else "PLANNED CHANGES")
    print("=" * 60)
    for module in MODULES:
        pages = [i for i in module["items"] if i["type"] == "Page"]
        print(f"\n📦 New module: {module['name']}  (unpublished - hidden from students)")
        print(f"   Position: bottom of the Modules page")
        if module.get("prerequisite"):
            print(f"   🔒 Locked until '{module['prerequisite']}' is completed")
        print(f"   New pages to create: {len(pages)} (also unpublished)")
        print(f"   Items: {len(module['items'])}")
        indents = compute_indents(module["items"])
        for n, (item, indent) in enumerate(zip(module["items"], indents), start=1):
            detail = item.get("external_url") or (
                f"content_id={item['content_id']}" if "content_id" in item else ""
            )
            if item["type"] == "Page":
                detail = "new page"
            if item.get("require"):
                detail = (detail + " | " if detail else "") + f"requirement: {item['require']}"
            pad = "  " * indent
            label = f"{n:>3}. {pad}[{item['type']}] {item['title']}"
            print(f"      {label}" + (f"\n           {detail}" if detail else ""))
    print("\n" + "=" * 60)
    print("Module 7 is NOT modified - nothing is moved, edited, or deleted.")
    print("=" * 60 + "\n")


def get_course():
    """Validate configuration and connect. Only called when actually writing -
    a dry run should work with no .env file at all."""
    if not all([CANVAS_URL, CANVAS_TOKEN, COURSE_ID_STR]):
        raise ValueError(
            "Missing required environment variables!\n"
            "Please ensure your .env file has:\n"
            "  - CANVAS_URL (e.g., https://your-institution.instructure.com)\n"
            "  - CANVAS_TOKEN (your API token from Canvas Settings)\n"
            "  - COURSE_ID (the course ID number, e.g., 123456)"
        )
    try:
        course_id = int(COURSE_ID_STR)
    except ValueError:
        raise ValueError(
            f"COURSE_ID must be a number, but got: {COURSE_ID_STR}\n"
            "Please check your .env file and use only digits for COURSE_ID"
        )

    print(f"🔗 Connecting to Canvas: {CANVAS_URL}")
    canvas = Canvas(CANVAS_URL, CANVAS_TOKEN)

    print(f"📚 Fetching course {course_id}...")
    course = canvas.get_course(course_id)
    print(f"✅ Connected to course: {course.name}\n")
    return course


def find_existing_module(course, name):
    """Return an existing module with this exact name, or None.

    Lets the script be re-run safely without creating duplicate modules.
    """
    for module in course.get_modules():
        if getattr(module, "name", None) == name:
            return module
    return None


def create_page(course, title, body):
    """Create an unpublished wiki page and return it.

    Pages are created unpublished so they stay hidden from students even
    though they are reachable from the course Pages index.
    """
    return course.create_page(wiki_page={
        "title": title,
        "body": body,
        "published": False,
    })


def build_module(course, spec, prerequisite_module_id=None):
    """Create one module, its pages, and its items. Returns the module's id
    (whether newly created or already existing), so callers can wire it up
    as another module's prerequisite."""
    existing = find_existing_module(course, spec["name"])
    if existing:
        print(f"↪️  Module '{spec['name']}' already exists (id {existing.id}) - skipping.")
        return existing.id

    module_payload = {"name": spec["name"], "published": False}
    if prerequisite_module_id:
        module_payload["prerequisite_module_ids"] = [prerequisite_module_id]

    # position is omitted so Canvas appends the module at the bottom.
    module = course.create_module(module=module_payload)
    lock_note = f", locked behind module {prerequisite_module_id}" if prerequisite_module_id else ""
    print(f"📦 Created module '{spec['name']}' (id {module.id}, unpublished{lock_note})")

    indents = compute_indents(spec["items"])
    for item, indent in zip(spec["items"], indents):
        payload = {"type": item["type"], "title": item["title"], "indent": indent}

        if item["type"] == "Page":
            page = create_page(course, item["title"], item["body"])
            payload["page_url"] = page.url
            print(f"      📄 Created page '{item['title']}' ({page.url}, unpublished)")
        elif item["type"] == "ExternalUrl":
            payload["external_url"] = item["external_url"]
            payload["new_tab"] = True
        elif "content_id" in item:
            payload["content_id"] = item["content_id"]

        if item.get("require"):
            payload["completion_requirement"] = {"type": item["require"]}

        module.create_module_item(module_item=payload)
        req_note = f" (requires {item['require']})" if item.get("require") else ""
        print(f"      ✅ [{item['type']}] {item['title']}{req_note}")

    print(f"🎉 Module '{spec['name']}' complete: {CANVAS_URL}/courses/{course.id}/modules\n")
    return module.id


def main():
    parser = argparse.ArgumentParser(
        description="Split Module 7 into separate CSS Grid and CSS Flexbox modules."
    )
    parser.add_argument(
        "--apply", action="store_true",
        help="Actually connect to Canvas and create the modules (after confirmation). "
             "Without this flag, it's a dry run only."
    )
    args = parser.parse_args()

    print_plan(dry_run=not args.apply)

    if not args.apply:
        print("This was a dry run - no connection to Canvas was made and nothing was created.")
        print("Re-run with --apply to actually create the modules.")
        return

    course = get_course()

    if not confirm(f"Create {len(MODULES)} unpublished modules in '{course.name}'?"):
        print("Aborted. Nothing was created.")
        return

    module_ids = {}
    for spec in MODULES:
        prereq_id = module_ids.get(spec.get("prerequisite"))
        module_ids[spec["name"]] = build_module(course, spec, prerequisite_module_id=prereq_id)


if __name__ == "__main__":
    try:
        main()
    except Exception as e:
        print(f"\n❌ Error occurred:")
        print(f"   {e}")
        print(f"\nCommon issues:")
        print(f"   - Invalid COURSE_ID: Check that the course ID exists")
        print(f"   - Invalid token: Your API token may have expired")
        print(f"   - Permission denied: Your account may not have access to this course")
        raise
